#!/bin/bash

REPO_DIRECTORY="$( dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

if [ ! -L "$REPO_DIRECTORY/.git/hooks" ]; then
    if [ -d "$REPO_DIRECTORY/.git/hooks-original" ]; then
        rm -rf "$REPO_DIRECTORY/.git/hooks"
    else
        mv "$REPO_DIRECTORY/.git/hooks" "$REPO_DIRECTORY/.git/hooks-original"
    fi

    ln -s "../.githooks" "$REPO_DIRECTORY/.git/hooks"
fi
